using System.Net;
using RemoteControl.Net.Turn;
using Xunit;

namespace RemoteControl.Net.Tests.Turn;

public class TurnMessageTests
{
    /// <summary>
    /// The strongest test here, and the reason it exists: RFC 5769's published vectors cover
    /// Binding only, and StunMessageTests had to strip MESSAGE-INTEGRITY and FINGERPRINT from
    /// the one it uses. So there is no official vector for the part of TURN most likely to be
    /// wrong -- the two length fix-ups (the header length must already count MESSAGE-INTEGRITY
    /// when its HMAC is computed, then already count FINGERPRINT when its CRC is computed) and
    /// the long-term key derivation.
    ///
    /// These bytes were generated by a separate Python implementation written from RFC
    /// 5389/5766, using hashlib and zlib rather than anything in this codebase. That makes this
    /// a cross-implementation check on layout, coverage and both fix-ups. What it cannot prove
    /// is that the RFC was read correctly by both -- only a real coturn can settle that, and
    /// nothing here has spoken to one.
    /// </summary>
    [Fact]
    public void Build_MatchesAnIndependentReferenceImplementation()
    {
        var transactionId = new byte[12];
        for (var i = 0; i < transactionId.Length; i++) transactionId[i] = (byte)i;

        var key = TurnMessage.LongTermKey("app-user", "remote-control.local", "s3cret");
        var message = TurnMessage.Build(
            TurnMethod.Allocate,
            StunClass.Request,
            transactionId,
            [
                TurnMessage.BuildRequestedTransportUdp(),
                TurnMessage.BuildLifetime(600),
                TurnMessage.BuildStringAttribute(TurnMessage.UsernameAttribute, "app-user"),
                TurnMessage.BuildStringAttribute(TurnMessage.RealmAttribute, "remote-control.local"),
                TurnMessage.BuildStringAttribute(TurnMessage.NonceAttribute, "abcd1234"),
            ],
            key);

        byte[] expected =
        {
            0x00, 0x03, 0x00, 0x60, 0x21, 0x12, 0xA4, 0x42, 0x00, 0x01, 0x02, 0x03,
            0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x00, 0x19, 0x00, 0x04,
            0x11, 0x00, 0x00, 0x00, 0x00, 0x0D, 0x00, 0x04, 0x00, 0x00, 0x02, 0x58,
            0x00, 0x06, 0x00, 0x08, 0x61, 0x70, 0x70, 0x2D, 0x75, 0x73, 0x65, 0x72,
            0x00, 0x14, 0x00, 0x14, 0x72, 0x65, 0x6D, 0x6F, 0x74, 0x65, 0x2D, 0x63,
            0x6F, 0x6E, 0x74, 0x72, 0x6F, 0x6C, 0x2E, 0x6C, 0x6F, 0x63, 0x61, 0x6C,
            0x00, 0x15, 0x00, 0x08, 0x61, 0x62, 0x63, 0x64, 0x31, 0x32, 0x33, 0x34,
            0x00, 0x08, 0x00, 0x14, 0xC8, 0x16, 0xA9, 0x89, 0x3E, 0xD2, 0x25, 0xBC,
            0x39, 0x79, 0xA1, 0xF6, 0xF7, 0xA0, 0xC2, 0x89, 0x06, 0xAC, 0xC8, 0x66,
            0x80, 0x28, 0x00, 0x04, 0xD4, 0x2E, 0x5E, 0x62,
        };

        Assert.Equal(expected, message);
    }

    [Theory]
    [InlineData(TurnMethod.Allocate, StunClass.Request, 0x0003)]
    [InlineData(TurnMethod.Allocate, StunClass.SuccessResponse, 0x0103)]
    [InlineData(TurnMethod.Allocate, StunClass.ErrorResponse, 0x0113)]
    [InlineData(TurnMethod.Refresh, StunClass.Request, 0x0004)]
    [InlineData(TurnMethod.CreatePermission, StunClass.Request, 0x0008)]
    [InlineData(TurnMethod.Send, StunClass.Indication, 0x0016)]
    [InlineData(TurnMethod.Data, StunClass.Indication, 0x0017)]
    public void Build_EncodesTheMessageTypesFromRfc5766(TurnMethod method, StunClass messageClass, int expectedType)
    {
        // The method/class split is interleaved through the 14 type bits rather than being two
        // clean fields, so these are worth pinning against the values the RFC names directly.
        var message = TurnMessage.Build(method, messageClass, TurnMessage.NewTransactionId(), []);

        Assert.Equal(expectedType, (message[0] << 8) | message[1]);
        Assert.True(TurnMessage.TryParse(message, out var parsed));
        Assert.Equal(method, parsed.Method);
        Assert.Equal(messageClass, parsed.Class);
    }

    [Fact]
    public void TryParse_ReadsARelayedAddressBackOutOfAnAllocateSuccess()
    {
        var transactionId = TurnMessage.NewTransactionId();
        var relayed = new IPEndPoint(IPAddress.Parse("203.0.113.9"), 49155);
        var mapped = new IPEndPoint(IPAddress.Parse("198.51.100.4"), 51000);

        var response = TurnMessage.Build(
            TurnMethod.Allocate, StunClass.SuccessResponse, transactionId,
            [
                TurnMessage.BuildXorAddress(TurnMessage.XorRelayedAddressAttribute, relayed),
                TurnMessage.BuildXorAddress(TurnMessage.XorMappedAddressAttribute, mapped),
                TurnMessage.BuildLifetime(600),
            ]);

        Assert.True(TurnMessage.TryParse(response, out var parsed));
        Assert.Equal(relayed, parsed.RelayedEndpoint);
        Assert.Equal(mapped, parsed.MappedEndpoint);
        Assert.Equal(600u, parsed.LifetimeSeconds);
    }

    [Fact]
    public void TryParse_DecodesErrorCodeAsClassAndNumber()
    {
        // ERROR-CODE is not an integer: the hundreds digit lives in the low 3 bits of byte 2 and
        // the remainder in byte 3, so a naive read gives 1 instead of 401.
        var errorValue = new byte[] { 0, 0, 4, 1 };
        var message = TurnMessage.Build(
            TurnMethod.Allocate, StunClass.ErrorResponse, TurnMessage.NewTransactionId(),
            [
                TurnMessage.BuildAttribute(TurnMessage.ErrorCodeAttribute, errorValue),
                TurnMessage.BuildStringAttribute(TurnMessage.RealmAttribute, "remote-control.local"),
                TurnMessage.BuildStringAttribute(TurnMessage.NonceAttribute, "nonce-value"),
            ]);

        Assert.True(TurnMessage.TryParse(message, out var parsed));
        Assert.Equal(401, parsed.ErrorCode);
        Assert.Equal("remote-control.local", parsed.Realm);
        Assert.Equal("nonce-value", parsed.Nonce);
    }

    [Fact]
    public void TryParse_RejectsDatagramsThatAreNotStun()
    {
        // The relay path shares one socket with the media stream, so "not ours" has to be a
        // cheap false rather than an exception -- a video shard must not be able to throw here.
        Assert.False(TurnMessage.TryParse(new byte[] { 1, 2, 3 }, out _));
        Assert.False(TurnMessage.TryParse(new byte[40], out _)); // zeroed: no magic cookie
    }
}
